# Generated by Django 5.2.16 on 2026-08-03 21:28

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-posta')),
                ('ad_soyad', models.CharField(blank=True, max_length=80, verbose_name='ad soyad')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='yönetim paneline erişebilir')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='katılma tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'kullanıcı',
                'verbose_name_plural': 'kullanıcılar',
                'ordering': ['ad_soyad', 'email'],
            },
            managers=[
                ('objects', apps.accounts.models.KullaniciYoneticisi()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.avatar_yolu, verbose_name='profil fotoğrafı')),
                ('avatar_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='avatar kimliği')),
                ('mevki', models.CharField(blank=True, choices=[('', 'Belirtilmemiş'), ('kaleci', 'Kaleci'), ('defans', 'Defans'), ('orta_saha', 'Orta saha'), ('forvet', 'Forvet')], default='', max_length=20, verbose_name='mevki')),
                ('forma_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='forma numarası')),
                ('hakkinda', models.CharField(blank=True, max_length=160, verbose_name='kısa not')),
                ('ortalama_puan', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ortalama puan')),
                ('puan_sayisi', models.PositiveIntegerField(default=0, verbose_name='aldığı puan sayısı')),
                ('oynanan_mac', models.PositiveIntegerField(default=0, verbose_name='oynadığı maç')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profiller',
            },
        ),
    ]
