# Generated by Django 5.2.16 on 2026-08-14 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('groups', '0002_grup_asist_gosterilsin_grup_gol_gosterilsin_and_more'),
        ('matches', '0004_mac_forma_golu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('tur', models.CharField(choices=[('fotograf', 'Maç fotoğrafı'), ('mesaj', 'Sohbet mesajı')], max_length=20, verbose_name='tür')),
                ('sebep', models.CharField(choices=[('mustehcen', 'Müstehcenlik veya çıplaklık'), ('siddet', 'Şiddet veya tehdit'), ('taciz', 'Hakaret, taciz veya nefret söylemi'), ('spam', 'Spam veya alakasız içerik'), ('diger', 'Diğer')], max_length=20, verbose_name='sebep')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='açıklama')),
                ('mesaj_metni', models.TextField(blank=True, verbose_name='bildirilen metin')),
                ('durum', models.CharField(choices=[('bekliyor', 'İnceleniyor'), ('kaldirildi', 'İçerik kaldırıldı'), ('reddedildi', 'Kural ihlali bulunmadı')], db_index=True, default='bekliyor', max_length=12, verbose_name='durum')),
                ('karar_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='karar tarihi')),
                ('karar_notu', models.CharField(blank=True, max_length=300, verbose_name='karar notu')),
                ('bildiren', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirdigi_icerikler', to=settings.AUTH_USER_MODEL, verbose_name='bildiren')),
                ('fotograf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sikayetler', to='matches.macfotografi', verbose_name='fotoğraf')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sikayetler', to='groups.grup', verbose_name='grup')),
                ('inceleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inceledigi_sikayetler', to=settings.AUTH_USER_MODEL, verbose_name='inceleyen')),
                ('mesaj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sikayetler', to='chat.mesaj', verbose_name='mesaj')),
            ],
            options={
                'verbose_name': 'şikâyet',
                'verbose_name_plural': 'şikâyetler',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['grup', 'durum', '-olusturulma'], name='moderation__grup_id_bf197b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fotograf__isnull', False)), fields=('bildiren', 'fotograf'), name='fotograf_basina_tek_sikayet'), models.UniqueConstraint(condition=models.Q(('mesaj__isnull', False)), fields=('bildiren', 'mesaj'), name='mesaj_basina_tek_sikayet')],
            },
        ),
    ]
