# Generated by Django 5.2.16 on 2026-08-03 21:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('ad', models.CharField(max_length=60, verbose_name='grup adı')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('genel_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kurucu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurdugu_gruplar', to=settings.AUTH_USER_MODEL, verbose_name='kurucu')),
            ],
            options={
                'verbose_name': 'grup',
                'verbose_name_plural': 'gruplar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='DavetBagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('jeton_ozet', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='jeton özeti')),
                ('etiket', models.CharField(blank=True, max_length=60, verbose_name='etiket')),
                ('son_kullanma', models.DateTimeField(db_index=True, verbose_name='son kullanma')),
                ('max_kullanim', models.PositiveSmallIntegerField(default=25, verbose_name='azami kullanım')),
                ('kullanim_sayisi', models.PositiveSmallIntegerField(default=0, verbose_name='kullanım sayısı')),
                ('iptal_edildi', models.BooleanField(default=False, verbose_name='iptal edildi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_davetler', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davetler', to='groups.grup', verbose_name='grup')),
            ],
            options={
                'verbose_name': 'davet bağlantısı',
                'verbose_name_plural': 'davet bağlantıları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='Uyelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('rol', models.CharField(choices=[('uye', 'Üye'), ('yonetici', 'Yönetici')], default='uye', max_length=10, verbose_name='rol')),
                ('durum', models.CharField(choices=[('bekliyor', 'Onay bekliyor'), ('onayli', 'Onaylı'), ('reddedildi', 'Reddedildi'), ('ayrildi', 'Ayrıldı')], default='bekliyor', max_length=12, verbose_name='durum')),
                ('katilma_notu', models.CharField(blank=True, max_length=200, verbose_name='katılma notu')),
                ('karar_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='karar tarihi')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyelikler', to='groups.grup', verbose_name='grup')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyelikler', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayladigi_uyelikler', to=settings.AUTH_USER_MODEL, verbose_name='onaylayan')),
            ],
            options={
                'verbose_name': 'üyelik',
                'verbose_name_plural': 'üyelikler',
                'ordering': ['-rol', 'kullanici__ad_soyad'],
                'indexes': [models.Index(fields=['grup', 'durum'], name='groups_uyel_grup_id_7cef15_idx')],
                'constraints': [models.UniqueConstraint(fields=('grup', 'kullanici'), name='benzersiz_grup_uyeligi')],
            },
        ),
    ]
