# Generated by Django 5.2.16 on 2026-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grup',
            name='asist_gosterilsin',
            field=models.BooleanField(default=False, verbose_name='asistler gösterilsin'),
        ),
        migrations.AddField(
            model_name='grup',
            name='gol_gosterilsin',
            field=models.BooleanField(default=False, verbose_name='goller gösterilsin'),
        ),
        migrations.AddField(
            model_name='grup',
            name='kart_gosterilsin',
            field=models.BooleanField(default=False, verbose_name='kartlar gösterilsin'),
        ),
    ]
