# Generated by Django 5.2.16 on 2026-08-03 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deger', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puan')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puanlar', to='matches.mac', verbose_name='maç')),
                ('puanlanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldigi_puanlar', to=settings.AUTH_USER_MODEL, verbose_name='puanlanan')),
                ('puanlayan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdigi_puanlar', to=settings.AUTH_USER_MODEL, verbose_name='puanlayan')),
            ],
            options={
                'verbose_name': 'puan',
                'verbose_name_plural': 'puanlar',
                'indexes': [models.Index(fields=['puanlanan'], name='ratings_pua_puanlan_662c5b_idx'), models.Index(fields=['mac', 'puanlanan'], name='ratings_pua_mac_id_90aff6_idx')],
                'constraints': [models.UniqueConstraint(fields=('mac', 'puanlayan', 'puanlanan'), name='mac_basina_tek_puan'), models.CheckConstraint(condition=models.Q(('puanlayan', models.F('puanlanan')), _negated=True), name='kendine_puan_verilemez'), models.CheckConstraint(condition=models.Q(('deger__gte', 1), ('deger__lte', 10)), name='puan_1_10_arasinda')],
            },
        ),
    ]
