# Generated by Django 5.2.16 on 2026-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puan',
            name='karantinada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='karantinada'),
        ),
    ]
