# Generated by Django 5.2.16 on 2026-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_puan_karantinada'),
    ]

    operations = [
        migrations.AddField(
            model_name='puan',
            name='yazim_sayisi',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='yazım sayısı'),
        ),
    ]
