# Generated by Django 5.2.16 on 2026-08-03 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('katilma_istegi', 'Katılma isteği'), ('katilma_onaylandi', 'Katılma onaylandı'), ('katilma_reddedildi', 'Katılma reddedildi'), ('yonetici_yapildi', 'Yönetici yapıldı'), ('yeni_mac', 'Yeni maç'), ('mac_guncellendi', 'Maç güncellendi'), ('mac_iptal', 'Maç iptal edildi'), ('yoklama_acildi', 'Yoklama açıldı'), ('puanlama_acildi', 'Puanlama açıldı'), ('gruptan_cikarildi', 'Gruptan çıkarıldı')], max_length=24, verbose_name='tür')),
                ('baslik', models.CharField(max_length=120, verbose_name='başlık')),
                ('mesaj', models.CharField(blank=True, max_length=250, verbose_name='mesaj')),
                ('hedef_url', models.CharField(blank=True, max_length=250, verbose_name='hedef')),
                ('okundu', models.BooleanField(db_index=True, default=False, verbose_name='okundu')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to=settings.AUTH_USER_MODEL, verbose_name='alıcı')),
            ],
            options={
                'verbose_name': 'bildirim',
                'verbose_name_plural': 'bildirimler',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['alici', 'okundu', '-olusturulma'], name='notificatio_alici_i_462d0c_idx')],
            },
        ),
    ]
