# Generated by Django 5.2.16 on 2026-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildirim',
            name='tur',
            field=models.CharField(choices=[('katilma_istegi', 'Katılma isteği'), ('katilma_onaylandi', 'Katılma onaylandı'), ('katilma_reddedildi', 'Katılma reddedildi'), ('yonetici_yapildi', 'Yönetici yapıldı'), ('yeni_mac', 'Yeni maç'), ('mac_guncellendi', 'Maç güncellendi'), ('mac_iptal', 'Maç iptal edildi'), ('yoklama_acildi', 'Yoklama açıldı'), ('puanlama_acildi', 'Puanlama açıldı'), ('gruptan_cikarildi', 'Gruptan çıkarıldı'), ('supheli_oylama', 'Şüpheli oylama'), ('puanlarin_silindi', 'Puanların silindi'), ('macin_adami', 'Maçın adamı')], max_length=24, verbose_name='tür'),
        ),
    ]
