# Generated by Django 5.2.16 on 2026-08-28 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_bildirim_tur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushAbonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='uç adres')),
                ('p256dh', models.CharField(max_length=255, verbose_name='p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='auth')),
                ('tarayici', models.CharField(blank=True, max_length=200, verbose_name='tarayıcı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='eklenme')),
                ('son_kullanim', models.DateTimeField(blank=True, null=True, verbose_name='son başarılı gönderim')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_abonelikleri', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'push aboneliği',
                'verbose_name_plural': 'push abonelikleri',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['kullanici'], name='notificatio_kullani_e9137c_idx')],
            },
        ),
    ]
