# Generated by Django 5.2.16 on 2026-08-03 21:28

import apps.matches.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('baslangic', models.DateTimeField(db_index=True, verbose_name='tarih ve saat')),
                ('konum', models.CharField(blank=True, max_length=120, verbose_name='saha / konum')),
                ('notlar', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('sure_dakika', models.PositiveSmallIntegerField(default=60, verbose_name='süre (dakika)')),
                ('yoklama_acik', models.BooleanField(default=True, verbose_name='yoklama açık')),
                ('yoklama_son', models.DateTimeField(blank=True, null=True, verbose_name='yoklama son tarihi')),
                ('iptal', models.BooleanField(default=False, verbose_name='iptal edildi')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maclar', to='groups.grup', verbose_name='grup')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_maclar', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'maç',
                'verbose_name_plural': 'maçlar',
                'ordering': ['-baslangic'],
            },
        ),
        migrations.CreateModel(
            name='Katilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('yanit', models.CharField(choices=[('geliyorum', 'Geliyorum'), ('yokum', 'Yokum'), ('belki', 'Belki')], max_length=10, verbose_name='yanıt')),
                ('katildi', models.BooleanField(blank=True, default=None, null=True, verbose_name='sahaya çıktı')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimlar', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimlar', to='matches.mac', verbose_name='maç')),
            ],
            options={
                'verbose_name': 'katılım',
                'verbose_name_plural': 'katılımlar',
            },
        ),
        migrations.CreateModel(
            name='MacFotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('dosya', models.ImageField(upload_to=apps.matches.models.mac_foto_yolu, verbose_name='dosya')),
                ('dosya_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aciklama', models.CharField(blank=True, max_length=120, verbose_name='açıklama')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='matches.mac', verbose_name='maç')),
                ('yukleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yukledigi_fotograflar', to=settings.AUTH_USER_MODEL, verbose_name='yükleyen')),
            ],
            options={
                'verbose_name': 'maç fotoğrafı',
                'verbose_name_plural': 'maç fotoğrafları',
                'ordering': ['olusturulma'],
            },
        ),
        migrations.AddIndex(
            model_name='mac',
            index=models.Index(fields=['grup', '-baslangic'], name='matches_mac_grup_id_2f30c4_idx'),
        ),
        migrations.AddIndex(
            model_name='katilim',
            index=models.Index(fields=['mac', 'yanit'], name='matches_kat_mac_id_cff864_idx'),
        ),
        migrations.AddConstraint(
            model_name='katilim',
            constraint=models.UniqueConstraint(fields=('mac', 'kullanici'), name='benzersiz_katilim'),
        ),
    ]
