# Generated by Django 5.2.16 on 2026-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katilim',
            name='takim',
            field=models.CharField(blank=True, choices=[('a', 'A Takımı'), ('b', 'B Takımı')], default='', max_length=1, verbose_name='takım'),
        ),
        migrations.AddField(
            model_name='mac',
            name='skor_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='A takımı skoru'),
        ),
        migrations.AddField(
            model_name='mac',
            name='skor_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='B takımı skoru'),
        ),
    ]
