# Generated by Django 5.2.16 on 2026-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_katilim_takim_mac_skor_a_mac_skor_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='katilim',
            name='asist',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='asist'),
        ),
        migrations.AddField(
            model_name='katilim',
            name='gol',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='gol'),
        ),
        migrations.AddField(
            model_name='katilim',
            name='kirmizi_kart',
            field=models.BooleanField(default=False, verbose_name='kırmızı kart'),
        ),
        migrations.AddField(
            model_name='katilim',
            name='poz_x',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='saha konumu X'),
        ),
        migrations.AddField(
            model_name='katilim',
            name='poz_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='saha konumu Y'),
        ),
        migrations.AddField(
            model_name='katilim',
            name='sari_kart',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='sarı kart'),
        ),
    ]
