# Generated by Django 5.2.16 on 2026-08-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_katilim_asist_katilim_gol_katilim_kirmizi_kart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mac',
            name='forma_golu',
            field=models.CharField(blank=True, choices=[('a', 'A Takımı'), ('b', 'B Takımı')], default='', max_length=1, verbose_name='forma golü'),
        ),
    ]
