# Generated by Django 5.2.16 on 2026-08-28 21:19

import apps.matches.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_mac_forma_golu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaylasilanFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('dosya', models.ImageField(upload_to=apps.matches.models.paylasilan_foto_yolu, verbose_name='dosya')),
                ('dosya_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paylasilan_fotograflar', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'paylaşılan fotoğraf',
                'verbose_name_plural': 'paylaşılan fotoğraflar',
                'ordering': ['olusturulma'],
                'indexes': [models.Index(fields=['kullanici', 'olusturulma'], name='matches_pay_kullani_6b69cf_idx')],
            },
        ),
    ]
