# Generated by Django 5.2.16 on 2026-08-03 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnahtarCifti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('acik_anahtar', models.TextField(verbose_name='açık anahtar (JWK)')),
                ('sifreli_ozel_anahtar', models.TextField(verbose_name='şifreli özel anahtar')),
                ('tuz', models.CharField(max_length=64, verbose_name='tuz (base64)')),
                ('iv', models.CharField(max_length=32, verbose_name='IV (base64)')),
                ('yineleme', models.PositiveIntegerField(verbose_name='PBKDF2 yineleme sayısı')),
                ('parmak_izi', models.CharField(blank=True, max_length=95, verbose_name='parmak izi')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anahtar_cifti', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'anahtar çifti',
                'verbose_name_plural': 'anahtar çiftleri',
            },
        ),
        migrations.CreateModel(
            name='GrupAnahtari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('guncellenme', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('surum', models.PositiveIntegerField(verbose_name='sürüm')),
                ('aktif', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('dondurulmeli', models.BooleanField(default=False, verbose_name='döndürülmeli')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sohbet_anahtarlari', to='groups.grup', verbose_name='grup')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_sohbet_anahtarlari', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
            ],
            options={
                'verbose_name': 'grup sohbet anahtarı',
                'verbose_name_plural': 'grup sohbet anahtarları',
                'ordering': ['-surum'],
            },
        ),
        migrations.CreateModel(
            name='AnahtarPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarmalanmis', models.TextField(verbose_name='sarmalanmış anahtar')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anahtar_paketleri', to=settings.AUTH_USER_MODEL, verbose_name='üye')),
                ('grup_anahtari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paketler', to='chat.grupanahtari', verbose_name='grup anahtarı')),
            ],
            options={
                'verbose_name': 'anahtar paketi',
                'verbose_name_plural': 'anahtar paketleri',
            },
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anahtar_surum', models.PositiveIntegerField(verbose_name='anahtar sürümü')),
                ('sifreli_metin', models.TextField(verbose_name='şifreli metin')),
                ('iv', models.CharField(max_length=32, verbose_name='IV (base64)')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='gönderilme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderdigi_mesajlar', to=settings.AUTH_USER_MODEL, verbose_name='gönderen')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='groups.grup', verbose_name='grup')),
            ],
            options={
                'verbose_name': 'mesaj',
                'verbose_name_plural': 'mesajlar',
                'ordering': ['olusturulma'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupanahtari',
            constraint=models.UniqueConstraint(fields=('grup', 'surum'), name='benzersiz_anahtar_surumu'),
        ),
        migrations.AddIndex(
            model_name='anahtarpaketi',
            index=models.Index(fields=['uye', 'grup_anahtari'], name='chat_anahta_uye_id_483d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='anahtarpaketi',
            constraint=models.UniqueConstraint(fields=('grup_anahtari', 'uye'), name='uye_basina_tek_paket'),
        ),
        migrations.AddIndex(
            model_name='mesaj',
            index=models.Index(fields=['grup', '-olusturulma'], name='chat_mesaj_grup_id_5a3e2f_idx'),
        ),
    ]
