# Generated by Django 5.2.16 on 2026-08-28 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnahtarDegisimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_parmak_izi', models.CharField(blank=True, max_length=95, verbose_name='eski parmak izi')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='zaman')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anahtar_degisimleri', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
            options={
                'verbose_name': 'anahtar değişimi',
                'verbose_name_plural': 'anahtar değişimleri',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['kullanici', '-olusturulma'], name='chat_anahta_kullani_79af68_idx')],
            },
        ),
    ]
